language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=precise
    - TOX_ENV=trunk
    - TOX_ENV=pypy

matrix:
    allow_failures:
        - env: TOX_ENV=pypy

install:
    - ./.travis-install.sh

script:
    - tox -e $TOX_ENV

notifications:
    irc:
        channels:
            - "irc.freenode.org#scrapy"
        use_notice: true
        skip_join: true
