platform: x86
version: '{branch}-{build}'
environment:
  matrix:
    - PYTHON: "C:\\Python36"
      TOX_ENV: py36

branches:
  only:
    - master
    - /d+\.\d+\.\d+[\w\-]*$/

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET TOX_TESTENV_PASSENV=HOME USERPROFILE HOMEPATH HOMEDRIVE"
  - "pip install -U tox twine wheel"
build: false
test_script:
  - "tox -e %TOX_ENV%"
