name: Checks
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: "3.11"
          env:
            TOXENV: security
        - python-version: "3.11"
          env:
            TOXENV: flake8
        # Pylint requires installing reppy, which:
        # - Does not support Python 3.9: https://github.com/seomoz/reppy/issues/122
        # - Requires CLang to build https://github.com/seomoz/reppy/issues/132
        - python-version: 3.8
          env:
            CC: clang
            TOXENV: pylint
        - python-version: 3.7
          env:
            TOXENV: typing
        - python-version: "3.11"  # Keep in sync with .readthedocs.yml
          env:
            TOXENV: docs
        - python-version: "3.11"
          env:
            TOXENV: twinecheck

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Run check
      env: ${{ matrix.env }}
      run: |
        pip install -U tox
        tox
